Repository Eustachekamala/Asset-Inventory-Management-F-end, pull requests merged in 2024-11, with the labels that each got.

#9 asset management, dashboard admin
  client/src/App.jsx
  client/src/components/AdminDashboard.jsx
  client/src/components/Asset/AssetForm.jsx
  client/src/components/Auth/Login.jsx
  client/src/components/EmployeeDashboard.jsx
  client/src/components/ProcurementManagerDashboard.jsx
  client/src/components/Request/RequestList.jsx
Labels: good first issue

#11 Fix Navbar state access error by adding optional chaining for userInf…
  client/src/App.jsx
  client/src/components/AdminDashboard.jsx
  client/src/components/Asset/AssetForm.jsx
  client/src/components/Auth/Login.jsx
  client/src/components/Navbar.jsx
  client/src/components/PrivateRoute.jsx
  client/src/components/Unauthorized.jsx
  client/src/redux/authSlice.js
  client/src/redux/store.js
  client/src/redux/userSlice.js
Labels: documentation

#12 Dev
  client/src/App.jsx
  client/src/components/AdminDashboard.jsx
  client/src/components/Asset/AssetForm.jsx
  client/src/components/Auth/Login.jsx
  client/src/components/Navbar.jsx
  client/src/components/PrivateRoute.jsx
  client/src/components/Unauthorized.jsx
  client/src/redux/authSlice.js
  client/src/redux/store.js
  client/src/redux/userSlice.js
Labels: bug

#15 added error handling and updated all files under the request folder
  client/src/App.jsx
  client/src/components/Request/RequestForm.jsx
  client/src/components/Request/RequestHistory.jsx
  client/src/components/Request/RequestList.jsx
Labels: bug

#16 Ft tracking
  client/src/App.jsx
Labels: bug

#17 Resolved conflict to the branch of ft-tracking
  client/src/App.jsx
  client/src/components/Auth/Login.jsx
  client/src/components/PrivateRoute.jsx
  client/src/components/Request/RequestForm.jsx
  client/src/components/Request/RequestHistory.jsx
  client/src/components/Request/RequestList.jsx
Labels: documentation

#18 Ft asset management
  client/package-lock.json
  client/package.json
  client/src/components/Auth/Login.jsx
Labels: bug

#19 Dev
  client/package-lock.json
  client/package.json
  client/src/components/Auth/Login.jsx
Labels: bug

#20 Ft tracking
  client/src/App.jsx
  client/src/components/Request/RequestStatus.jsx
Labels: documentation

#21 Ft tracking
  client/src/App.jsx
  client/src/components/Request/RequestStatus.jsx
Labels: documentation
